apiVersion: apps/v1
kind: Deployment
metadata:
  name: applyservice
  labels:
    app: applyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applyservice
  template:
    metadata:
      labels:
        app: applyservice
    spec:
      containers:
        - name: applyservice
          image: "username/applyservice:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
